### ISSUE TITLE
Benötigst Du Hilfe?

### ISSUE THREAD

**Issue by wizzardking** [cytec/nzb.to-nZEDb#1]
Hallo Cytec

Danke für all den Support in den letzen Jahren.
Ich verstehe absolut, weswegen du das Board geschlossen hast. Das gute hierbei ist aber, dass sich die verschiedenen Tools so weiterentwickelt hatten, dass Dein Fork an sich nicht mehr notwendig war und es lediglich dadurch ruhiger auf cytec.us wurde.

Die direkte nzb.to Anbindung vermisse ich aber seither natürlich schon etwas. Kann ich Dich hier irgendwie unterstützen um dies zum laufen zu bringen?

lg
wizzi

**Comment by cytec** [comment]
Was die Tools angeht, hast du recht, ich bin nicht böse darum. Ganz im Gegenteil es wurde immer mehr in die entsprechenden Originale übernommen so das mein Fork eingentlich immer mehr und mehr obsolet wurde. Die deutschen Daten gibt's weiterhin und die bekommt man auch in das Tool seiner Wahl und den nzb.to Provider kann jetzt auch jeder selbst hosten.

Also mit PHP 5 sollte das alles eigentlich ohne Probleme laufen, mit PHP 7 wahrscheinlich nicht mehr, da gibt's einige der Funktionen nicht mehr bzw. wurden umbenannt etc.

EDIT: ich glaube @WebBuddha hat das ganze schon irgendwo am laufen ;)

**Comment by hypePG** [comment]
Hey Ihr @wizzardking @cytec !

Tut mir leid, wenn ich den issuetracker jetzt mal missbrauche, aber habe gerade echt gestaunt, dass ich euch hier wiedergefunden habe :D mich hat es witzigerweise über folgende diskussion hierher verschlagen: https://github.com/SickChill/SickChill/issues/4984 

habt ihr das theater "um unser geliebtes sickbeard" mitbekommen? habe die cytec community leider irgendwann aus den augen verloren, aber letztens die alten server inklusive, damals noch sb und co mal wieder ausgemottet. da ist mir aufgefallen, wie sehr ich doch das gute alte wizznab und den sickbeard german fork vermisse :D ich war auf beiden plattformen damals mit dem gleichen usernamen unterwegs. vllt. erinnert man sich ja noch ;) 

plane zurzeit mit einem guten kollegen mal wieder nen eigenen indexer aufzusetzen. falls interesse oder neugier besteht, meldet euch doch.

viele grüße und alles gute!

**Comment by WebBuddha** [comment]
Ich frag mich schon, wie du aus der Diskussion hier gelandet bist? ;-)

**Comment by cytec** [comment]
@WebBuddha naja es gab damals ne ähnliche Aktion und SR hatte sich geteilt, wahrscheinlich ist ihm das dadurch wieder eingefallen :D

**Comment by hypePG** [comment]
@WebBuddha ganz genau, hab durch die diskussion mien setup mal wiederbelebt, und dann @cytec gestalked ;) alles gute für euch
