### ISSUE TITLE
Kein Connect von Couchpotato zum WebServer

### ISSUE THREAD

**Issue by BMWfan** [cytec/nzb.to-nZEDb#10]
Hallo cytec,

danke erstmal für das coole Projekt.

Ich habe nun alles soweit installiert und die beiden Docker Container am laufen:
nzbto-nzedb_torproxy_1
nzbto-nzedb_nzbtoproxy_1

Leider bekomme ich beim Aufruf der Website kein Inhalt.

Ich habe testweise eine Test html Website erstellen und mit a2ensite aktiviert, diese ist ganz normal erreichbar.

Das Error log zeigt folgenden Fehler:
`[Fri Jul 26 10:21:02.801693 2019] [:error] [pid 433] [client 192.168.0.66:61683] PHP Fatal error:  Uncaught  --> Smarty: unable to write file /var/www/httpdocs/libs/smarty//templates_c/wrt5d3ad40ec3a402.19341450 <-- \n  thrown in /var/www/httpdocs/libs/smarty/sysplugins/smarty_internal_write_file.php on line 4`

Gruß 

Daniel

**Comment by anonvoy** [comment]
Hatte ich auch, ist ein Rechte-Problem im Docker-Container mit dem Apache: Der apache im Docker-Container läuft als Benutzer www-data, der zur Benutzergruppe www-data gehört. Deswegen kann er die Datei nicht in das Verzeichnis schreiben, das Benutzer 1000 aus der Gruppe users gehört.

Abhilfe: In der Konsole in den Docker-Container wechseln (_docker exec -it nzbto-nzedb_nzbtoproxy_1 bash_) und dort dann _chown -R www-data:www-data /var/www_. Dann sollte alles funktionieren, bei mir war es jedenfalls so.

**Comment by BMWfan** [comment]
@anonvoy Danke dir.

Leider renn ich direkt in den nächsten Fehler nachdem ich ein User und Passwort angelegt habe:
`[Sat Jul 27 07:01:05.751302 2019] [:error] [pid 12] [client 192.168.0.59:50051] PHP Fatal error:  Call to undefined function mcrypt_get_iv_size() in /var/www/httpdocs/inc/security.php on line 9, referer: http://192.168.0.100/`

Hattest du das auch, oder wüsstest du eine Lösung?

**Comment by anonvoy** [comment]
Da bin ich leider überfragt. Müssen wohl die Profis ran :-)

**Comment by cytec** [comment]
@BMWfan das sieht aus als wäre die php mcrypt extension nicht da... sicher dass du den richtigen container nutzt? eigentlich sollte das installiert und auch aktiviert sein...

Versuch mal dich auf den Container zu verbinden und das manuell zu installieren:

```
apt-get install php5-mcrypt
php5enmod mcrypt
service apache2 restart
```

**Comment by BMWfan** [comment]
@cytec, hab ich schon gemacht. Hat auch funktioniert. Konnte den von dir genutzten php-apache Container nicht nehmen, da mein Raspberry Pi zwecks unterschiedlichen Kernel den nicht nehmen wollte. Habe es wie du es beschrieben hast aber gestern nach langem probieren zum laufen gebracht. Danke dir. Kurze Frage noch, was hat es mit dem SALT_Key auf sich, also wofür wird der benötigt?

**Comment by cytec** [comment]
@BMWfan das erklärt's natürlich ;)
Der SALT_KEY wird verwendet um aus deinem Passwort und Benutzernamen einen API Key zu erstellen den du dann in diversen tools hinterlegen kannst.
Den Key solltest du unbedingt ändern! Jeder der den Key hat kommt entsprechend an deine Zugangsdaten (wenn er den apikey hat)

EDIT: hab auch nen Hinweis auf mcrypt in die Readme gepackt ;)

**Comment by BMWfan** [comment]
@cytec Danke, adde doch folgende zwei Zeilen (direkt nach der COPY Zeile) in dein Dockerfile, damit erschlägst du gleich zwei Fehler:

`RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf`
`RUN chown -R www-data:www-data /var/www`

Diese zwei habe ich (direkt darunter) hinzugefügt um das php-extension Problem zu lösen:

`RUN apt-get update && apt-get install -y  libmcrypt-dev libreadline-dev`
`RUN docker-php-ext-install mcrypt`

**Comment by cytec** [comment]
Der chown ist eigentlich nicht nötig (wenn du das per git clone installierst) ;) 
und die php extension ist in dem Paket auf dem das aufbaut eigentlich schon dabei... 

Ich habe mal mit dem Gedanken gespielt das ganz noch etwas kleiner aufzuziehen mit nem arch linux oder ähnlichem... mal schauen, wenn ich die Zeit und muse dazu finde mach ich das vll noch...
