### ISSUE TITLE
Radarr kann API nicht verwenden

### ISSUE THREAD

**Issue by BMWfan** [cytec/nzb.to-nZEDb#11]
Hi cytec,

ich bin nun von couchpotato auf radarr umgestigen, da couchpotato ja meines Wissens nach nicht wirklich mehr weiterentwickelt wird. Leider scheint radarr die API anzufragen von deinem Docker Container
`172.23.0.1 - - [05/Aug/2019:13:47:55 +0000] "GET /api?t=movie&cat=2000&extended=1&apikey=herausgelöscht-zur-sicherheit&offset=0&limit=100 HTTP/1.1" 200 783 "-" "Radarr/0.2.0.1358 (Linux 4.19)"` aber ohne Erfolg:
![2019-08-05 15_56_06-Window](https://user-images.githubusercontent.com/5577540/62470188-2976aa00-b79a-11e9-8b20-03aa7c23497a.png)

Was könnte da das Problem sein?

**Comment by wizzardking** [comment]
Hatte das selbe Problem. Hab nun aber für alle indexer NZBHydra 2 zwischen Indexer und Sonarr/Radarr gehängt und damit ist das Problem von alleine verschwunden.
NZB Hydra ist so oder so sehr nützlich im Setup zu haben.

**Comment by BMWfan** [comment]
@wizzardking danke für deine Antwort. Würde nur schon gerne direkt den Container ansprechen wollen und nicht über Umwege falls möglich. Zumindest wird in der Beschreibung davon gesprochen das auch die requests von Radarr behandelt werden, ggf. ist noch eine zusätzliche Einstellung von Nöten.

**Comment by cytec** [comment]
@BMWfan ich hab keine Ahung, prinzipiell wird das nZEDb API Format benutzt, welches soweit ich weiß auch in sonarr/radarr etc eingebunden ist. Allerdings scheint es da wie @wizzardking schon sagte probleme zu geben. Irgendwas scheint radarr da anders zu erwarten als es ist. Leider weiß ich nicht genau was das wäre...

IMHO hast du zwei möglichkeiten:
1. Du machst bei denen nen Ticket auf und fragst wieso das net geht (am besten mit nem BSP wie die Antwort deines Servers auf das query aussieht wenn dus im Browser auf machst) je nach dem kann ich da dann was anpassen
2. Du hängst nzbhydra dazwischen

**Comment by BMWfan** [comment]
@cytec ich würde gerne ersteres versuchen und werde dich hier auf dem Laufenden halten. 
Wenn nichts dagegen spricht, würde es mich freuen wenn wir grundsätzlich das Tool etwas optimieren könnten in Sachen Treffer bei der Suche. Bin jetzt kein Programmierer, aber wäre bereit dir Inputs zu liefern und mit dir gemeinsam daran zu arbeiten und daraus zu lernen.

**Comment by cytec** [comment]
Ich bin gespannt was dabei raus kommt ;) 
Was das optimieren der Suche angeht, gestaltet sich das ganze als recht schwer... ich hab kein account mehr und generell war das problem das nzbto ihren releases keine imdb id's zuweist.. daher auch der "umweg" über themoviedb und die suche nach den Film titeln

**Comment by BMWfan** [comment]
@cytec das ist kein Problem. Wir können das ja gemeinsam machen indem wir es bei mir dann testen, falls es für dich in Ordnung geht.

**Comment by ghost** [comment]
ich werde die tage mal mein script hack ein wenig aufräumen und dann pushen
der funzt auch tadelos mit radarr. Wieso auch immer hab ich bereits
vergessen :D :D.

**Comment by BMWfan** [comment]
@r0x0r316 das wäre perfekt. Gib Bescheid wenn du soweit bist.

**Comment by BMWfan** [comment]
@r0x0r316 konntest du schon schauen ?

**Comment by BMWfan** [comment]
@cytec ich habe es zum laufen gebracht. Aber nur durch Zufall eigentlich. Ich habe den externen Port auf 8080 gestellt da 80 bei mir schon belegt war durch einen anderen Docker Container. Siehe da, es funktioniert auch mit Radarr. Wann hättest du denn mal Zeit zwecks Verbesserung der Suchergebnisse?

**Comment by ghost** [comment]
> @r0x0r316 das wäre perfekt. Gib Bescheid wenn du soweit bist.

bescheid @BMWfan

**Comment by BMWfan** [comment]
> 
> 
> > @r0x0r316 das wäre perfekt. Gib Bescheid wenn du soweit bist.
> 
> bescheid @BMWfan

Danke. Ich habe dein Container mal deployed, jedoch wird auf der Seite nichts angezeigt. 
Das ist die Fehlermeldung aus dem Log: 
`192.168.0.182 - - [17/Nov/2019:12:03:46 +0100] "GET / HTTP/1.1" 500 211 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"`
