### ISSUE TITLE
Error wenn config.inc.php nicht existiert

### ISSUE THREAD

**Issue by cytec** [cytec/nzb.to-nZEDb#3]
Aktuell wird ein 500er Fehler Produziert.
Im Idealfall sollte eine Meldung angezeigt werden die dem User sagt, dass er die Datei entsprechend bearbeiten muss.

**Comment by STX2k** [comment]
Hab den gleichen Fehler. Aber mit bearbeitet config.inc.php Datei. Log Dateien werden auch nicht angelegt. Nutze die Docker Version.

**Comment by cytec** [comment]
git clone oder file download?

**Comment by STX2k** [comment]
Git clone

**Comment by cytec** [comment]
was sagen denn die error logs von apache/php?

schreibrechte auf die entsprechenden Ordner sind vorhanden?

**Comment by STX2k** [comment]
### **EDIT: Okay fixxed -.-**
templates_c Ordner hatte keine Schreibrechte :>

Das ist ja die Sache, Error Logs werden nicht mal angelegt. Hier mal noch ein paar Infos:

- Ubuntu 18.04
- Docker version 18.09.0, build 4d60db4

Hab unter meinem docker User einmal die git gecloned, die Config angepasst und dann im Hauptverzeichniss `docker-compose up` startet auch alles soweit ohne Errors.

der Apache Container startet soweit ich das sehen kann Problemlos 

```
*** open logfile,
*** Run files in /etc/my_runonce/,
*** Running /etc/my_runonce/00_dump_info.sh...,
Build of nimmis/ubuntu:14.04, date: 2018-04-12T20:11:23Z,
*** Running /etc/my_runonce/50_set_timezone...,
timezone not set, trying to autodetect,
external ip is 1XX.XX3.XXX.XXX,
timezone should be Europe/Berlin,
setting timezone to Europe/Berlin,
*** Run files in /etc/my_runalways/,
*** Running /etc/rc.local...,
*** Booting supervisor daemon...,
*** Supervisor started as PID 26,
2019-01-07 20:00:54,352 CRIT Set uid to user 0,
*** Started processes via Supervisor......,
apache2                          RUNNING    pid 31, uptime 0:00:04,
crond                            RUNNING    pid 30, uptime 0:00:04,
syslog-ng                        RUNNING    pid 29, uptime 0:00:04,
,,
n,
*** Shutting down supervisor daemon (PID 26)...,
*** Killing all processes...,
*** open logfile,
*** Run files in /etc/my_runonce/,
*** Run files in /etc/my_runalways/,
*** Running /etc/rc.local...,
*** Booting supervisor daemon...,
*** Supervisor started as PID 10,
2019-01-08 16:33:12,866 CRIT Set uid to user 0,
*** Started processes via Supervisor......,
apache2                          RUNNING    pid 15, uptime 0:00:04,
crond                            RUNNING    pid 14, uptime 0:00:04,
syslog-ng                        RUNNING    pid 13, uptime 0:00:04,
,
``` 
Wenn ich auf die IP+Port gehe (bei mir ist der 80 Port auf 3331 gelegt) bekomme ich einfach nur einen: 

HTTP ERROR 500

im Verzeichniss `stx@ares:~/docker/nzb.to-nZEDb/logs$` werden gar keine Logs angelegt. Weder Error noch Access. Wenn ich mich aber auf den Container verbinde, gibt es da paar logs.

``` 
[Tue Jan 08 16:33:14.013145 2019] [mpm_prefork:notice] [pid 33] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.24 configured -- resuming normal operations
[Tue Jan 08 16:33:14.013185 2019] [core:notice] [pid 33] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 08 16:35:57.342310 2019] [:error] [pid 36] [client 79.245.198.240:43366] PHP Fatal error:  Uncaught  --> Smarty: unable to write file /var/www/httpdocs/libs/smarty//templates_c/wrt5c34c35d538e81.41679222 <-- \n  thrown in /var/www/httpdocs/libs/smarty/sysplugins/smarty_internal_write_file.php on line 44
tail: unrecognized file system type 0x794c7630 for 'error.log'. please report this to bug-coreutils@gnu.org. reverting to polling
```

**Comment by STX2k** [comment]
Hab aber trotzdem noch ne frage. Müssen irgendwelche Berechtigungen gesetzt werden? Hab jetzt meine Login Daten eingegeben, finden tut er nix und im Admin Panel im Main Log steht auch nix. 

**EDIT:** 
Habt jetzt im Container nochmal die rechte angepasst. Jetzt funzt es :) 
Vielen dank für diesen Proxy - Endlich wieder **B indexen ;D

**Comment by cytec** [comment]
im logs Ordner sind nur die logs der Anwendung an sich ;)
hast die richtige Zeile im apache log ja gefunden!
