### ISSUE TITLE
Suchanfragen wird nicht durchgeführt 

### ISSUE THREAD

**Issue by razmauser** [cytec/nzb.to-nZEDb#4]
Hi. Ich habe das Script via Docker laufen und via SickChill eingebunden. 

Allerdings sehe ich im cache, nur die ersten 50 Einträge der TV Shows von nzb.to und es wird nichts gefunden. Es scheint so, also ob die Suchparameter ignoriert werden die von der Suchanfragen kommen. 
Jemand nen Tipp?

**Comment by cytec** [comment]
Das wird das normale update sein, der zieht nur die letzten 50 Einträge periodisch, wenn du manuell suchst sollte es gehen bzw wenn das tool deiner Wahl eine konkrete Suchanfrage stellt

**Comment by razmauser** [comment]
Hmm. In welcher log Datei kann ich denn prüfen, ob die manuelle Suchanfragen korrekt ankommt?

**Comment by cytec** [comment]
entweder in den access logs des apaches oder im log Order in der Datei nzbto2newznab.txt
