### ISSUE TITLE
Falsche URL wird genutzt

### ISSUE THREAD

**Issue by speridal** [cytec/nzb.to-nZEDb#5]
Hallo zusammen,

ich habe den Docker-Container soweit am Laufen. Leider funktioniert die Integration in Sickrage nicht. Im Sickrage Logfile sehe ich, dass folgende Meldung: 

Request failed: 404 Client Error: Not Found for url: http://servername:82/api?apikey=**********&t=caps

Wenn ich mir die index.php anschaue, dann wird dort die URL http://servername:82/index.php?site=api&apikey=****************&t=caps erwartet

Hat jemand eine Idee, was ich falsch mache?

Danke.

Gruß,
Speridal

**Comment by cytec** [comment]
Alles korrekt. Das wird per htaccess und ModRewrite geregelt siehe https://github.com/cytec/nzb.to-nZEDb/blob/master/httpdocs/.htaccess#L8 

Das die Url nicht gefunden wird ist allerdings tatsächlich komisch.

**Comment by speridal** [comment]
Hmm, den Apikey konnte ich über die Seite generieren und hab diesen auch in Sickrage eingetragen. Kann ich vielleicht noch irgendwo anders in Logs gucken? Vielleicht klappt das rewrite nicht?

**Comment by cytec** [comment]
Du kannst im logs Ordner gucken, oder halt in die apache logs des docker containers

**Comment by speridal** [comment]
Okay, hab es gefunden. Ich hatte Probleme mit der Webseite im Docker Container, daher hatte ich außerhalb einen virtuellen Webserver genutzt. Mein Problem war, dass Port 80 schon belegt war.
Ich hab jetzt rausgefunden, wie ich im Docker Container den Port ändern kann und jetzt läuft alles.
Danke für die schnelle Hilfe cytec!

**Comment by cytec** [comment]
Gerne! Freut mich das es klappt :)
