### ISSUE TITLE
Suchanfrage liefert falsche kategorie

### ISSUE THREAD

**Issue by ghost** [cytec/nzb.to-nZEDb#6]
In Hydra werden die einzelnen Fähigkeiten (maze/tvdb usw) nicht erkannt und zudem liefert er für die Ergebnisse durchgehend Kategorie:1000 (console) ab. Suchanfragen funktionieren ansonsten wie erwartet. Einzelne Kategorien lassen sich leider nicht wählen bei der Suche.

**Comment by cytec** [comment]
Was für Fähigkeiten? Generell ist es nicht wirklich verlässlich möglich nach irgend welchen ID's zu suchen, was daran liegt das nzb.to das nicht unterstütz (bei filmen wird das halbwegs umgangen per tmdb api) wenn das jemand implementiert nehme ich den PR gerne an, ich nutze weder Hydra noch nzb.to daher war das von meiner Seite nicht dir Priorität.

Kategorien sollten eigentlich zwischen TV, Movie und Games unterscheiden werden, das hatte auch verlässlich geklappt als ich das in diversen Tools getestet habe (Hydra gehörte da nicht dazu)

**Comment by ghost** [comment]
Vielen Dank für die schnelle Antwort.
Falls Hydra nicht bekannt ist es ist eine art Metacrawler für newsindexer, zentral alle indexer rein oder torrent tracker und nur hydra und hydra api in sonarr usw. rein.
Also laut deinen TPLs liefert dein Proxy das alles ab. Da muss irgendwo ein Problem vorliegen (evtl neue templates bzw xml für das suchen mit Mazeid TVDBid usw). Ich hab Hydra nun angewiesen die jeweiligen IDs selber in suchfähige begriffe umzuwandeln, das funktioniert ganz klasse und gibt auch die vorgesehene Kategorie zurück. Ich hab Hydra genutzt da Radarr und sonarr den Proxy nicht angenommen haben. Beide Scheitern schon beim adden. Über Hydra funktioniert es jedoch erkennt er nicht dass er über tmdbid usw. suchen kann. Da es so funktioniert wie es nun eingestellt ist, würde ich sagen es ist gelöst. Eventuell schaue ich die Tage noch mal rein und probiere das suchen per ids zu implementieren. Würde dann aber vom setup ne menge ändern da zusätzliche api keys. Lohnt nicht wirklich.

**Comment by cytec** [comment]
Cool! Wenn du dazu kommst, mach gerne nen PR!

**Comment by ghost** [comment]
Hab das was ich vor 6 monaten geschrieben hab nun mal geuppt damit ist das hier closed ;)
Falls dir das zuviel Fremdbiblis sind lass den pull request einfach und ich pull dann erst bei der finalen version wieder. ;)
