### ISSUE TITLE
nzb passwort mit leerzeichen und doppeltes pw

### ISSUE THREAD

**Issue by ghost** [cytec/nzb.to-nZEDb#7]
nzb.to bekommt es anscheinend seit jahren nicht hin verünftig formatierte rlses mitsamt {{password}} hinzubekommen. Habe nun in deinem wrapper/proxy in der index.php Anpassungen gemacht und geforked. In der Version wird dann das Passwort komplett aus dem Titel genommen und wie von dir vorgesehen in den nzb header gepackt (sehr schöne Lösung übrigens), werde im Laufe der Zeit den code verschönern (extra vars urghs) aber musste gestern schnell gehen. So wie ich etwas Zeit habe versuche ich für TV tvrage api einzubauen und werde auch die formatierung der Titel versuchen in ein szene taugliches format zu bringen, so das tools ala sonnarr und radarr es leichter haben.

**Comment by cytec** [comment]
ja die Passwörter bei nzb.to waren schon immer ein leidiges Thema. ich hab das damals so gut wie möglich abzufangen aber war abzusehen das es nur eine frage der Zeit ist bis das wieder vermehrt Probleme macht.

Ich bin gespannt auf deine Lösung!

**Comment by ghost** [comment]
kann eigentlich schon übernommen werden. hab hier nun bei meinem privaten build schon angefangen das script php7 kompatibel zu machen. hab ewig nichts mehr geschrieben ist ne schöne kleine anwendung um wieder reinzukommen ;)
